### ISSUE TITLE
fog/aws runtime dependency not specified in .gemspec

### ISSUE THREAD

**Issue by carlosipe** [rogercampos/saviour#21]
/lib/saviour/s3_storage.rb is requiring fog/aws. Either this wasn't intended either the .gemspec is missing a runtime dependency.
See:

`gem install saviour`
`ruby -e 'require "saviour"'`
`[..].rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require': cannot load such file -- fog/aws (LoadError)`

**Comment by carlosipe** [comment]
I've seen it's fixed at https://github.com/rogercampos/saviour/commit/1d0015ad3cd7a3e7b3ac7ff72146319c950584e6 but not released yet. As is, the gem is broken. Time for 0.4.2? :)

**Comment by rogercampos** [comment]
I'll do a new patch release 😛

**Comment by carlosipe** [comment]
:+1:
