### ISSUE TITLE
Impossible to use `Saviour::StringSource` with `update_attribute`

### ISSUE THREAD

**Issue by danigonza** [rogercampos/saviour#23]
The AR `after_save` callback that saves the file is expecting that the file exists. This does not happens when we use Saviour::StringSource in combination with `update_attribute`. Example:
```ruby
update_attribute!(:file_column, Saviour::StringSource.new(conetent, 'filename.pdf'))
```

This is raising `RuntimeError Exception: File does not exists`

The solution is very unconformable:

```ruby
resource.file_column = Saviour::StringSource.new(conetent, 'filename.pdf')
resource.file_column.write
resource.save!
```

**Comment by rogercampos** [comment]
I can't reproduce this, do you have more info?
